### ISSUE TITLE
Create installers for Shuriken and APIs

### ISSUE THREAD

**Issue by Fare9** [Fare9/Shuriken-Analyzer#26]
With cmake is possible to add commands for installing the different artifacts generated during the compilation. In this case the idea is installing all the header files to a header directory, the library in a proper folder where the system can find it, and the APIs to paths where the interpreter (for example in the case of Python) can find the libraries and being included when writing a program/script with them.

**Comment by jeppojeps** [comment]
I have concluded a first research, I would like to use a package manager to pack everything and make Shuriken installable, through apt, brew, snap. What I will do as a first iteration is to decide locations on the system and use CMake. The issue of specializing a final package is maintenance of those. IMO the best way would be to use brew that is available for all the platforms. Though people may dislike it. We will talk about it in another issue.

**Comment by Fare9** [comment]
Okay, I think a first step should be being able to install it through the current compilation tool, after that, we can work in releases, because using a package manager for installing should be once we are publishing releases of the library also following version numbers.
