### ISSUE TITLE
Error: Process completed with exit code 100.

### ISSUE THREAD

**Issue by Fare9** [Fare9/Shuriken-Analyzer#32]
There's an error compiling in the GCC pipeline, the next error appears:

```
Error: Process completed with exit code 100.
```

Example of job with an error: https://github.com/Fare9/Shuriken-Analyzer/actions/runs/9100651167/job/25407937453

**Comment by sisco0** [comment]
Reason behind the current unwanted behavior might be related to the unavailability of `gcc-11` package under _focal_ Ubuntu 20.04 version.
Would vote for upgrading _Ubuntu_ version to _noble_ 24.04.

**Comment by Fare9** [comment]
Accepted the Merge Request, I agree that having an updated version will be better. We can work later in adding old versions.
