### ISSUE TITLE
Python API get_method_by_name throws ValueError if no method is found

### ISSUE THREAD

**Issue by sidra-asa** [Fare9/Shuriken-Analyzer#55]
**Describe the bug**
The Python API `get_method_by_name` throws `ValueError: NULL pointer access` if no method is found.

**To Reproduce**
1. Put [DexParserTest.dex](https://github.com/Fare9/Shuriken-Analyzer/blob/main/shuriken/tests/compiled/DexParserTest.dex) in the current working directory.
2. Run the following code to use `get_method_by_name` to find a method that does not exist.

```
import re
from shuriken import *


if __name__ == '__main__':
    dex = Dex("DexParserTest.dex")
    dex.disassemble_dex()
    dex.create_dex_analysis(1)
    dex.analyze_classes()

    print(dex.get_method_by_name("METHOD_THAT_DOES_NOT_EXIST"))
```

Here is the result.
![image](https://github.com/user-attachments/assets/685acd75-6378-4311-9c4e-e51c791aac9e)

**Expected behavior**

Would it be possible to have `get_method_by_name` return None if the API finds no matching method?

Compared to ValueError, the None value makes the API easy to use because we don't need a try/except statement to process the None value. Also, returning None enables the API to be compatible with some Python features, like list comprehension. If the suggestion is considered acceptable, it would further enhance the usability of it.

**Comment by Fare9** [comment]
I assign someone to work on it, also I will assign it to add the feature of `is_external_api`. @jeppojeps will work on it. Thank you very much.

**Comment by Fare9** [comment]
Need to replace a few things in the C Core API to avoid exceptions, it is not solved yet. I will work on it.

**Comment by Fare9** [comment]
C Core API should return NULL in order to avoid exceptions, and Python should return None in that case.

**Comment by Fare9** [comment]
The main issue is fixed, but I have seen other possible fixes, this weekend I think I will be able to fix all of them!

**Comment by Fare9** [comment]
I have added a few more checks:

```
>>> dex.get_analyzed_class("NONEXISTINGCLASS") is None
True
>>> dex.get_analyzed_method("NONEXISTINGMETHOD") is None
True
>>> dex.get_disassembled_method("NONEXISTINGMETHOD") is None
True
```

**Comment by Fare9** [comment]
Issue should be fixed now! I have also replaced the flags from `char` to `int` so you can check them with ==0 and ==1, I close the issue.
