### ISSUE TITLE
Use of unsupported type hinting syntax for Python 3.9

### ISSUE THREAD

**Issue by zinwang** [Fare9/Shuriken-Analyzer#70]
Hello, I noticed that the Python APIs in ``shuriken/bindings/Python/shuriken/__init__.py`` use [the operator `|` on types](https://peps.python.org/pep-0604/)(e.g., [here](https://github.com/Fare9/Shuriken-Analyzer/blob/5a4b1f6685f76f343b23ea6927f33281f20aed37/shuriken/bindings/Python/shuriken/__init__.py#L143)), which is incompatible with Python 3.9. However, according to the [setup.py](https://github.com/Fare9/Shuriken-Analyzer/blob/5a4b1f6685f76f343b23ea6927f33281f20aed37/shuriken/bindings/Python/setup.py#L90), the APIs are supposed to support Python 3.9. Using this syntax may cause users of Python 3.9 to experience errors when running the APIs.

Replacing the syntax``X | Y`` with ``Union[X, Y]`` to maintain compatibility with Python 3.9 can solve the problem. Alternatively, updating setup.py to specify support for Python 3.10+ also works.

**Comment by Fare9** [comment]
Okay, I'm not much a python programmer, so I was not really sure about it. It seems that next year will be the end of life from Python 3.9, so probably I will specify the support for Python 3.10 in the setup.py, I think it shouldn't be an issue for many python programmers, and I suppose it is recommended to work in an updated version.
Thanks!

**Comment by Fare9** [comment]
I think we will update the python version, it will help us in maintenance, and I think since  you are rewriting the engine with Shuriken, maybe it could be useful for you to update to 3.10 too with the new version.
